Домашнее задание по разметке
htmlacademy-htmlcss/2295065-sedona-36 pull request #2
Opened 2023-01-27 21:48 UTC by Atnekeeva

2023-01-31 17:42 UTC, baileys-li requested changes

2023-01-31 17:42 UTC, baileys-li commented on catalog.html
> +        </a>
```suggestion
        <a href="#" class="button">
          <span class="visually-hidden">Большие карточки</span>
        </a>
        <a href="#" class="button">
          <span class="visually-hidden">Показать список</span>
        </a>
```

2023-01-31 17:42 UTC, baileys-li commented on catalog.html
> +      </section>
Форма не должна быть пустой (без кнопки сабмита). Закрой её и эту секцию после всех филдсетов и меню

2023-02-01 21:44 UTC, Atnekeeva commented on catalog.html
> +      </section>
Внесла правки

2023-02-04 10:04 UTC, merged