Домашнее задание 4
htmlacademy-htmlcss/2295065-sedona-36 pull request #4
Opened 2023-02-10 08:35 UTC by Atnekeeva

Привет! 
Направляю домашнее задание на главную страницу. Каталог пока не делала, хочу понять правильно ли я сделала стили на главной странице.

Возник вопрос при прикреплении фонового изображения в части:
"Подпишитесь на рассылку".
Не получается прикрепить фото, не понимаю, как правильно прописать.

2023-02-11 06:23 UTC, baileys-li requested changes
Отошлю полный разбор в ТГ

2023-02-11 06:23 UTC, baileys-li commented on index.html
> +        <img src="images/welcome.jpg" width="458" height="352" alt="Потому что Гранд Каньон отстой">
Неправильный формат. Надпись в макете векторная

2023-02-11 06:23 UTC, baileys-li commented on styles/styles.css
> +  font-display: swapp
```suggestion
  src: url("../fonts/ptsans-400.woff2") format("woff2");
  font-display: swap;
```

2023-02-11 06:23 UTC, baileys-li commented on styles/styles.css
> +  background-color: #FFFFFF;
```suggestion
   background-color: #ffffff;
```

2023-02-14 21:18 UTC, Atnekeeva commented
Внесла правки

2023-02-15 17:33 UTC, merged